### PR TITLE
[Plugin] submitting the attachmate plugin

### PR DESCRIPTION
**Pull request by zeeshantariq08**
I have created the attachment plugin that manages the attachments with polymorphic(morphMany) relation

### CODE REVIEW

**Review by saade — CHANGES_REQUESTED** [review]
Hey! Your docs needs to be written in the README.md file, also, ensure that image URLs in your plugin's `README` file are absolute URLs rather than relative links? Then we can embed them on our website correctly. Thanks!

Please let us know when you've addressed these issues.

**Comment by zeeshantariq08** [comment]
> Hey! Your docs needs to be written in the README.md file, also, ensure that image URLs in your plugin's `README` file are absolute URLs rather than relative links? Then we can embed them on our website correctly. Thanks!

@saade i have resolved the issues , what can i do now

**Review by zeeshantariq08 — COMMENTED** [review]
i have resolved the issues.

**Comment by zeeshantariq08** [comment]
> Hey! Could you please ensure that image URLs in your plugin's `README` file are absolute URLs rather than relative links? Then we can embed them on our website correctly. Thanks!
> 
> Also, please ensure that you Markdown can be rendered correcly, we've noticed broken syntax in your documentation, such as links.
> 
> Please let us know when you've addressed these issues.

Hi @saade , i have addressed these issues and it is resolved now, thank you!

**Review by saade — APPROVED** [review]
Hey! Your plugin's `README` is loaded into the plugin page on the Filament website. There is now a duplicate image on your page, as it also exists in your documentation. You can remove it from the Filament website by giving it a `filament-hidden` class, so then it is only shown once.

**Pull request merged**
