### PR TITLE
add Filament Simple Lightbox Plugin

### PR DESCRIPTION
**Pull request by lam0819**

### CODE REVIEW

**Comment by saade** [comment]
Hey! Please enable the option "Allow edits and access to secrets by maintainers" option here in the PR settings  👉🏼  to allow us to push changes to your PR.

**Review by saade — CHANGES_REQUESTED** [review]
Hey! Please enable the option "Allow edits and access to secrets by maintainers" option here in the PR settings 👉🏼 to allow us to push changes to your PR.

**Comment by lam0819** [comment]
> Hey! Please enable the option "Allow edits and access to secrets by maintainers" option here in the PR settings 👉🏼 to allow us to push changes to your PR.

I am not sure where to click the allow box.
seems i have no way to change this

**Comment by saade** [comment]
> > Hey! Please enable the option "Allow edits and access to secrets by maintainers" option here in the PR settings 👉🏼 to allow us to push changes to your PR.
> 
> I am not sure where to click the allow box. seems i have no way to change this

I am not sure if you can change this option after opening a PR, but the option should be visible here at the right column below "participants"

image

If you don't see this option, please re-submit your PR with this option enabled.

**Comment by lam0819** [comment]
> > > Hey! Please enable the option "Allow edits and access to secrets by maintainers" option here in the PR settings 👉🏼 to allow us to push changes to your PR.
> > 
> > 
> > I am not sure where to click the allow box. seems i have no way to change this
> 
> I am not sure if you can change this option after opening a PR, but the option should be visible here at the right column below "participants"
> 
> image
> If you don't see this option, please re-submit your PR with this option enabled.

image

seems no now.

**Pull request closed without merging**
