### PR TITLE
[New Plugin] Added Relaticle as author & Custom Fields plugin

### PR DESCRIPTION
**Pull request by ManukMinasyan**

### CODE REVIEW

**Comment by ManukMinasyan** [comment]
Hi @danharrin,

I've sent you an invitation to access the private repository `relaticle/custom-fields`.

Best regards.

**Comment by ManukMinasyan** [comment]
Hello @saade . When can I get the feedback? Thanks

**Review by saade — APPROVED** [review]
Hey! Thanks for your contribution. This is a first review that checks if everything is correct and inline with our guidelines. You've submited a paid plugin, therefore your private plugin repository needs to be reviewed by another team member before it can be fully merged and published on our website.

**Review by saade — CHANGES_REQUESTED** [review]
Hey! Could you please switch to using AnyStack instead of Lemon Squeezy for selling your plugin, as per our [README](https://github.com/filamentphp/filamentphp.com#selling-a-plugin)?

Let us know if you have any questions or need further assistance.

**Comment by ManukMinasyan** [comment]
> Hey! Could you please switch to using AnyStack instead of Lemon Squeezy for selling your plugin, as per our [README](https://github.com/filamentphp/filamentphp.com#selling-a-plugin)?
> 
> 
> 
> Let us know if you have any questions or need further assistance.

Hi! Thank you for answer, I can't switch to AnyStack because they are not supported Stripe Atlas as a connect account. In my country Stripe didn't have support, this is a reason I switched to LS.

**Comment by ManukMinasyan** [comment]
Hi @danharrin ,

Thanks for clarifying the need for AnyStack due to its affiliate program. I've registered my product on Lemon Squeezy with a 15% commission. Please try connecting it to your account and let me know if there are any issues or if further discussion is needed.

**Comment by danharrin** [comment]
Thank you

**Comment by ManukMinasyan** [comment]
@danharrin If the Lemon Squeezy integration works as expected, I can develop a simple platform similar to AnyStack that is compatible with Lemon Squeezy. I've already created a service that manages private packages and licenses using LM payments, so expanding on this should be feasible.

Let me know your thoughts on this approach.

**Comment by ManukMinasyan** [comment]
Hi @danharrin, @saade,

Hope you're well!  Could you update me on the review status or let me know when it might be published? If you need anything else from me, just let me know.

Thanks!

**Comment by danharrin** [comment]
Hi, Saade will let you know if he needs anything else for the review when it happens. Thanks.

**Review by saade — APPROVED** [review]

**Pull request merged**
