### PR TITLE
ADD: List TomatoPHP Plugins

### PR DESCRIPTION
**Pull request by 3x1io**
On This PR:

- Add Author Fady Mondy
- Add Plugin User Manager
- Add Plugin Translations Manager
- Add Plugin Menu Generator
- Add Plugin Developer Gate
- Add Plugin Settings Hub
- Add Plugin Alerts Sender
- Add Plugin File Browser
- Add Plugin Artisan Commands Runner
- Add Plugin Splade Integration
- Add Plugin Location Seeder
- Add Plugin Account Builder
- Add Plugin Wallet Manager
- Add Plugin Types Manager
- Add Plugin Plugin Manager & Generator

### CODE REVIEW

**Review by saade — CHANGES_REQUESTED** [review]
Hey!

1. Could you please ensure that image URLs in your plugin's `README` file are absolute URLs rather than relative links? Then we can embed them on our website correctly.

2. Your plugin image must fit the 16:9 aspect ratio, at least 2560x1440 pixels in size, and preferably a JPEG, as per our [Contributing Guide](https://github.com/filamentphp/filamentphp.com#submitting-a-plugin).

3. Also, we've renamed you plugins to match the plugin guidelines.
> The filename should be your author name, followed by the name of your plugin, with spaces replaced by dashes.
If you want to use "tomato-foo-bar", please submit a "tomato" author profile.

4. Please correct the `publish_date` of all your submited plugins. It should be the date that the plugin was originally released since you're upgrading them from v2.

Please let us know when you've addressed these issues.

**Comment by saade** [comment]
Also, i've renamed you plugins to match the guidelines on the README.

> The filename should be your author name, followed by the name of your plugin, with spaces replaced by dashes.

If you want to use "tomato-foo-bar", please submit a "tomato" author profile.

**Comment by 3x1io** [comment]
@saade thanks for your review i will fix it all and add more package and resubmit it for another review

**Comment by 3x1io** [comment]
Hey @saade it's done

1- all images on the Readme file have been updated to real link
2- all plugin images have been changed to 2560x1440 and jpg type
3- all plugins match the username [3x1io]
4- publish_date has been changed to the releases of support v3

please re-check it.

thanks for your support

**Comment by saade** [comment]
Hey. Thanks for the changes.

Regarding the publish_date, it should be the date you've submitted to the v2 website (or your plugin first release), not when you've updated them to v3.


I'll review the other changes later tonight

**Comment by 3x1io** [comment]
Okay I will update just 3 
- filament-menus 
- filament-users
- filament-translations

**Comment by 3x1io** [comment]
dates are done now you can review.

**Comment by 3x1io** [comment]
@saade any updates or comments?

**Comment by saade** [comment]
If you keep pushing new plugins to this PR, i'll continue delaying your review. Also, the dates needs to match the first release date not the date they're updated to v3.

Please let me know when i can proceed with the review

**Comment by 3x1io** [comment]
@saade it's already the release date and you can check the GitHub for this.

**Comment by saade** [comment]
> @saade it's already the release date and you can check the GitHub for this.

Yes, checking github:

tomato-browser: you've submitted the date `Apr 8, 2024`, your V3 plugin was re-tagged a release in `Sep 6, 2023`, but this plugin has been around since V2, more precisely `Apr 03, 2022`.

tomato-translations: you've submitted the date `Sep 28, 2023`, your plugin was released on `Feb 17, 2022`.

tomato-menus: Submitted date `Dec 20, 2023`, first release `Apr 3, 2022`.

...

What i meant is: You've submitted these plugins to the v2 website, simply moving them from your private account to a org, doesn't count as "new plugin".

**Comment by 3x1io** [comment]
It’s oky i will recheck all dates and resubmit a review again, and i’m so sorry that my PR is very big but I promise you the next one will be for only one plugin 😂

**Pull request closed without merging**
