### PR TITLE
Create francoism90-improve-laravel-scout-results.md

### PR DESCRIPTION
**Pull request by francoism90**
See https://github.com/filamentphp/filament/pull/8292#issuecomment-1712655055

If something is missing, please let me know. :)

### CODE REVIEW

**Comment by danharrin** [comment]
Hi, we will need an author profile, you can check in the README how to do that

**Comment by danharrin** [comment]
Hi again, we are missing your author image. Please read the README.

**Review by saade — CHANGES_REQUESTED** [review]
Hey! Your author image must be square and have dimensions of at least 1000x1000px as per our [Contributing Guide](https://github.com/filamentphp/filamentphp.com#setting-up-an-author-profile).

Please let us know when you've addressed these issues.

**Comment by saade** [comment]
Hey! Thanks for your interest in contributing with the community!

Due to the length of most community articles that get submitted, sometimes it takes a long time to review them for grammar and accuracy. We do not feel comfortable publishing them without that thorough review because they are given the same visibility as official articles, but we also have limited time and would prefer to use it improving the product. 

Because of that, we would prefer it if the community published articles themselves instead of through our official platform. If you don't have a personal blog or want to publish the article in a platform thats more involved with the Filament community, we can recommend you to use https://filamentglow.com.

**Pull request closed without merging**
