### PR TITLE
Add Pirsch analytics

### PR DESCRIPTION
**Pull request by zepfietje**
This PR adds Pirsch for analytics using the backend tracking integration.
I've configured it such that all routes in `web.php` will be tracked (so Filament admin for articles and such are not exposed).

Do you think we should exclude the feeds route as well, @danharrin?

### CODE REVIEW

**Comment by danharrin** [comment]
Does `TrackPageview` dispatch a job to the queue? Or is the HTTP request made before the response happens in the middleware

**Comment by zepfietje** [comment]
> Does `TrackPageview` dispatch a job to the queue? Or is the HTTP request made before the response happens in the middleware

It's a terminable middleware which sends the HTTP request after the response has been returned. So it should have no impact on loading times.

**Comment by danharrin** [comment]
Analytics for feeds could be useful idk

**Comment by zepfietje** [comment]
> Analytics for feeds could be useful idk

Yeah let's keep it and update if we run into anything.

**Pull request merged**
