### PR TITLE
[Plugin] Add "Minimalist" Theme Plugin + Author

### PR DESCRIPTION
**Pull request by angelej**

### CODE REVIEW

**Comment by saade** [comment]
Hey, could you please give @zepfietje access to the private repo so that he can review your theme properly.

**Comment by angelej** [comment]
> Hey, could you please give @zepfietje access to the private repo so that he can review your theme properly.

Done!

**Comment by angelej** [comment]
Is there anything I can do in order to speed up the review process?

**Review by zepfietje — CHANGES_REQUESTED** [review]
Hey @angelej, thanks for your patience! 😊

Your "Filament Minimalist Theme" seems to have a very similar goal as the official "Filament Minimal Theme". The name only differs two letters, which can't be a coincidence. Also, your docs seem to have been copied from the official Minimal Theme too.

We've discussed this internally in the Filament core team. For us to be able to list your plugin on the Filament site, we kindly request you rename your theme and rewrite the docs to avoid any confusion with the official "Filament Minimal Theme".

Aside from that, it might be good to clearly list which components are supported by your theme, since it only seems to style a subset of Filament's components. I think it's important to provide this information to not mislead potential users of your theme.

**Comment by angelej** [comment]
> Hey @angelej, thanks for your patience! 😊
> 
> Your "Filament Minimalist Theme" seems to have a very similar goal as the official "Filament Minimal Theme". The name only differs two letters, which can't be a coincidence. Also, your docs seem to have been copied from the official Minimal Theme too.
> 
> We've discussed this internally in the Filament core team. For us to be able to list your plugin on the Filament site, we kindly request you rename your theme and rewrite the docs to avoid any confusion with the official "Filament Minimal Theme".
> 
> Aside from that, it might be good to clearly list which components are supported by your theme, since it only seems to style a subset of Filament's components. I think it's important to provide this information to not mislead potential users of your theme.

Hi @zepfietje ,
thanks for reviewing this issue and the plugin!
I apologize for the inconvenience. This was absolutely not my intention.
Naming the plugin similar to the already existing "minimalistic" theme was a very bad idea.
Since they have very similar goals, I'm going to withdraw this PR / plugin, so there will be no confusion about the plugins.
Thank you very much for your valuable time and sorry again for the inconvenience!

**Pull request closed without merging**
