### PR TITLE
Add filament forms tinyeditor to plugins section

### PR DESCRIPTION
**Pull request by mohamedsabil83**

### CODE REVIEW

**Comment by danharrin** [comment]
Thanks. You can fix the images in your docs by making the URLs absolute I think

**Comment by mohamedsabil83** [comment]
You're welcome. I'll fix it.

**Comment by mohamedsabil83** [comment]
Fix it in my docs

**Comment by danharrin** [comment]
Nice, thanks

**Comment by mohamedsabil83** [comment]
You're welcome 👍🏽

**Pull request merged**
