### PR TITLE
Add initial dusk tests

### PR DESCRIPTION
**Pull request by assertchris**
This PR introduces Dusk testing, and the following tests:
- OK tests for home, plugins, articles, and consulting
- Version switcher test for docs

### CODE REVIEW

**Comment by assertchris** [comment]
It is possible, but there are associated costs why is why I held back.

**Comment by danharrin** [comment]
Oh, what sort of costs? Time?

**Comment by assertchris** [comment]
Sorry, I should have been more specific. So, it looks like free org accounts are limited to 2000 action minutes a month. Dusk test actions are pretty slow, and this change would make them happen on each push to each branch on this repo. I have no idea how many minutes are currently taken by the actions on this org.

To give a comparison, I have phpunit + dusk actions running on another repo (about 20 phpunit tests, 1 dusk test) and the actions take between 1.5 and 2.5 minutes each to run.

**Comment by danharrin** [comment]
I wonder if GitHub will increase the action minutes for large open source repos, as we also heavily use actions on filamentphp/filament

**Comment by danharrin** [comment]
I think we should allow them to run only for the `main` branch, and see how it goes. I've checked the `filamentphp` org Actions usage and I don't think our usage is being monitored properly. Let's see how it goes.

**Comment by assertchris** [comment]
Cool, will add to this PR then.

**Comment by danharrin** [comment]
Thanks Chris!

**Comment by assertchris** [comment]
@danharrin run into an issue with this. the docs generation is failing because the action is denied the ability to clone another repo. [This link](https://stackoverflow.com/questions/60222741/github-actions-and-git-clone-issue) suggests a couple things, the most promising of which is generate a key-pair and add the secret to the repo secrets (and public to an associated account ,as I understand it). Does this seem like something you'd be willing to set up?

**Comment by danharrin** [comment]
Try `secrets.GH_ACCESS_TOKEN`

**Comment by danharrin** [comment]
Hey, gonna close this but if you want to work on it again in the future just reopen and we'd gratefully accept :)

**Comment by assertchris** [comment]
Ahhh, this is the second issue closed like this today. I clearly have a problem with follow-through. 😅

**Comment by danharrin** [comment]
it's ok! its a big ask

**Pull request closed without merging**
