### PR TITLE
[Plugin] Filament Translatable Field

### PR DESCRIPTION
**Pull request by aessam13**
A plugin designed to manage translations and display selected fields in different languages.

### CODE REVIEW

**Review by saade — APPROVED** [review]
Hey! Could you please ensure that image URLs in your plugin's `README` file are absolute URLs rather than relative links? Then we can embed them on our website correctly. Thanks!

Please let us know when you've addressed these issues.

**Comment by aessam13** [comment]
@saade I already using raw github links `https://raw.githubusercontent.com/omar-haris/filament-timezone-field/main/docs/timezone-arabic.png`, do I need to change this ?

**Comment by saade** [comment]
You need to change in your readme, the website updates every hour

**Comment by aessam13** [comment]
We already using github raw links not relative in the [readme](https://github.com/34ML/Filament-Translatable-Field/edit/main/README.md)

**Pull request merged**
