### PR TITLE
new plugins and replace images

### PR DESCRIPTION
**Pull request by icetalker**

### CODE REVIEW

**Review by saade — CHANGES_REQUESTED** [review]
Hey! Could you please ensure that image URLs in your plugin's `README` file are absolute URLs rather than relative links? Then we can embed them on our website correctly.

Your plugin image must fit the 16:9 aspect ratio, at least 2560x1440 pixels in size, and preferably a JPEG, as per our [Contributing Guide](https://github.com/filamentphp/filamentphp.com#submitting-a-plugin).

Also, please correct any grammar or spelling mistakes you find in the README files. 

Please let us know when you've addressed these issues.

**Comment by icetalker** [comment]
Fixed, thanks!

**Review by saade — CHANGES_REQUESTED** [review]
Readme images for `picker` and `chatgpt bot` are still broken.

**Comment by icetalker** [comment]
These links has been updated.

**Review by saade — APPROVED** [review]

**Pull request merged**
