### PR TITLE
Add nested list plugin

### PR DESCRIPTION
**Pull request by invaders-xx**

### CODE REVIEW

**Comment by invaders-xx** [comment]
Hi!

How do I upload the new image ?

**Comment by invaders-xx** [comment]
Do not publish it yet, I found an issue and there is no reason to publish until solved

**Comment by invaders-xx** [comment]
Hi,

I think it should be okay now. Let me know if there are still issues.

**Review by invaders-xx — COMMENTED** [review]
Ready to review

**Review by saade — APPROVED** [review]

**Pull request merged**
