### PR TITLE
Add Guava Calendar plugin

### PR DESCRIPTION
**Pull request by lukas-frey**

### CODE REVIEW

**Review by saade — CHANGES_REQUESTED** [review]
Hey! Could you please ensure that image URLs in your plugin's `README` file are absolute URLs rather than relative links? Then we can embed them on our website correctly.

Also, We couldn't embed some of your videos in your README correctly. Please change it to a raw-HTML markup. It should look something like:

```html
<video width="320" height="240" controls>
  <source src=“RAW-VIDEO-URL-HERE” type="video/mp4">
</video>
```

Please let us know when you've addressed these issues.

**Comment by lukas-frey** [comment]
Changed relative images to absolute images.

Not sure which videos you mean, all videos are already in html markup. There are links underneath each html markup so that they can also be played in github readme.

**Comment by saade** [comment]
The Resources section and Plugin banner are not raw urls so they're not being rendered correctly.

**Comment by lukas-frey** [comment]
Ah, missed those. Should be changed now. Thanks.

**Comment by lukas-frey** [comment]
Can we also get a discord channel? There's a link on the plugin's page linking to it, but it's not there / not accessible.

**Comment by saade** [comment]
@lukas-frey We've hit the channels limit (500) on discord. We're working on cleaning old/archived channels so that new ones can be created. At the mean time, all new plugins won't have a channel. They will be created when we've manage to finish the cleanup.

**Comment by lukas-frey** [comment]
Ah ok, didn't know there's a limit. Thanks!

**Pull request merged**
