### PR TITLE
Docs partner header

### PR DESCRIPTION
**Pull request by zepfietje**
As previously discussed (@danharrin), this PR adds a note about the partners to the docs header just like on the Laravel site.
It randomly shows either Kirschbaum or Whizzy on every page load:

Screenshot 2024-08-29 at 17 41 41
Screenshot 2024-08-29 at 17 41 49

### CODE REVIEW

**Comment by danharrin** [comment]
Please add a close button with local storage persistence for your preference

**Comment by zepfietje** [comment]
What would the close button be needed for? Wouldn't that defeat the purpose of the banner?

**Comment by danharrin** [comment]
I think the banner is pretty distracting and the user should at least have a choice to regain that screen real estate

**Comment by zepfietje** [comment]
What about just scrolling it out of view?

**Comment by zepfietje** [comment]
Yeah, I moved it out of the header element so the banner scrolls away :)

**Comment by zepfietje** [comment]
This is ready to go now, @danharrin 🙂

**Pull request merged**
