### PR TITLE
Add mokhosh and his plugins

### PR DESCRIPTION
**Pull request by mokhosh**

### CODE REVIEW

**Comment by danharrin** [comment]
Hey, could you try again with the plugin images, they don't look as clean as I would like, maybe use https://banners.beyondco.de/ if you're stuck?

**Comment by danharrin** [comment]
Also for accessibility reasons, to stay in compliance with ADA, regarding the colors

**Comment by mokhosh** [comment]
Of course

**Comment by danharrin** [comment]
Much much better. Thanks

**Pull request merged**
