### PR TITLE
[Plugin] Voltra - filament-svg-avatar

### PR DESCRIPTION
**Pull request by Voltra**
This package provides a default avatar URL provider that uses inline SVG URLs

### CODE REVIEW

**Review by saade — CHANGES_REQUESTED** [review]
Hey! Could you please ensure that image URLs in your plugin's `README` file are absolute URLs rather than relative links? Then we can embed them on our website correctly. Thanks!

Please let us know when you've addressed these issues.

**Comment by Voltra** [comment]
Hi! I'm pretty sure they're all absolute URLs

**Comment by Voltra** [comment]
I have now also made all relative URLs in the README absolute

**Comment by aessam13** [comment]
@Voltra I had this issue before, you are using the image url in the README like this: `https://github.com/Voltra/filament-svg-avatar/blob/main/art/banner.jpeg` change it to `raw.githubusercontent.com` and it will work fine like this: `https://raw.githubusercontent.com/Voltra/filament-svg-avatar/main/art/banner.jpeg`.

I hope this will help you

**Comment by Voltra** [comment]
@saade It should be good now

**Review by saade — APPROVED** [review]
Hey! Your plugin's `README` is loaded into the plugin page on the Filament website. There is now a duplicate image on your page, as it also exists in your documentation. You can remove it from the Filament website by giving it a `filament-hidden` class, so then it is only shown once.

**Pull request merged**
