### PR TITLE
[Plugin] Filament 2FA

### PR DESCRIPTION
**Pull request by Baspa**

### CODE REVIEW

**Comment by Baspa** [comment]
Hey @saade, I fixed the URLs in the package and also changed the image in this PR. It's a PNG, is that a problem? Or do you want me to convert it to a JPG?

**Review by saade — CHANGES_REQUESTED** [review]
Hey! Could you please ensure that image URLs in your plugin's `README` file are absolute URLs rather than relative links? Then we can embed them on our website correctly. Thanks!

Please let us know when you've addressed these issues.

**Comment by saade** [comment]
> Hey @saade, I fixed the URLs in the package and also changed the image in this PR. It's a PNG, is that a problem? Or do you want me to convert it to a JPG?

not a problem.

**Comment by saade** [comment]
They're not, here's an example of a raw url
https://raw.githubusercontent.com/vormkracht10/filament-2fa/main/docs/two-factor-page.png

**Comment by Baspa** [comment]
Ah excuse me, didn't know that. I fixed them! @saade

**Pull request merged**
