### PR TITLE
Add Guava Knowledge Base plugin

### PR DESCRIPTION
**Pull request by lukas-frey**

### CODE REVIEW

**Review by saade — CHANGES_REQUESTED** [review]
Hey! We couldn't embed the video in your README correctly. Please change it to a raw-HTML markup. It should look something like:

```html
<video width="320" height="240" controls>
  <source src=“RAW-VIDEO-URL-HERE” type="video/mp4">
</video>
```
 Please let us know when you've addressed these issues.

**Comment by lukas-frey** [comment]
> Hey! We couldn't embed the video in your README correctly. Please change it to a raw-HTML markup. It should look something like:
> 
> ```
> <video width="320" height="240" controls>
>   <source src=“RAW-VIDEO-URL-HERE” type="video/mp4">
> </video>
> ```
> 
>  Please let us know when you've addressed these issues.

Done

**Comment by saade** [comment]
Hey! The video is still broken, it looks like the quotes are wrong in your readme file.

image

**Comment by lukas-frey** [comment]
fixed

**Review by saade — APPROVED** [review]

**Pull request merged**
