### PR TITLE
add quadrubo-model-settings plugin

### PR DESCRIPTION
**Pull request by Quadrubo**
This PR contains my author profile, a profile picture and the quadrubo-model-settings plugin.

The plugin allows users to have their model specific settings on a page, similar to the spatie-laravel-settings-plugin. However this uses model specific settings and not static application settings.

I plan to expand this in the future to allow an entry in the user menu, etc.
Thanks for considering :)

### CODE REVIEW

**Review by saade — CHANGES_REQUESTED** [review]
Hey! Your author image must be square and have dimensions of at least 1000x1000px as per our [Contributing Guide](https://github.com/filamentphp/filamentphp.com#setting-up-an-author-profile).

Also, your plugin doesn't have an image, please add images as per our [Contributing guide](https://github.com/filamentphp/filamentphp.com#submitting-a-plugin). They are mandatory. For plugins, you could use [Beyond Code's banner generator](https://banners.beyondco.de) to generate them.

Please let us know when you've addressed these issues.

**Comment by Quadrubo** [comment]
Hey,
I updated my image to be 1000x1000 and added the plugin image.

**Review by saade — CHANGES_REQUESTED** [review]
Hey! Your plugin image must be in a 16:9 aspect ratio and have dimensions of at least 2560x1440px as per our [Contributing Guide](https://github.com/filamentphp/filamentphp.com#submitting-a-plugin).

Please let us know when you've addressed these issues.

**Comment by Quadrubo** [comment]
@saade sorry, should be fine now :)

**Review by saade — APPROVED** [review]

**Pull request merged**
