### PR TITLE
Add new consulting page with Kirschbaum partnership

### PR DESCRIPTION
**Pull request by HassanZahirnia**
This PR is to add the new consulting page. **Only** to be merged by @danharrin

### CODE REVIEW

**Comment by zepfietje** [comment]
@danharrin @HassanZahirnia, I've reviewed my bio, replace the testimonial, tweaked some copy, and applied a couple fixes.

All looks good to me now.

Do you still want to optimize/convert the new testimonial client picture I added, @HassanZahirnia?

**Comment by HassanZahirnia** [comment]
@zepfietje The testimonial images are now inconsistent with eachother:
image

What was the goal here? The size and spacing is totally off.

Another note for the Kirschbaum section: the "And ..." caption should have stayed imo. Don't know why you removed it but now there is no indication that there are other experts other than Dan to answer questions. 
image

**Comment by zepfietje** [comment]
> @zepfietje The testimonial images are now inconsistent with eachother

They already were when I first checked this PR. 🤔
You mean the size, right?
All I did was replace the image, nothing else design-wise.

> What was the goal here? The size and spacing is totally off.

No idea, I think @danharrin touched it?

> Another note for the Kirschbaum section: the "And ..." caption should have stayed imo. Don't know why you removed it but now there is no indication that there are other experts other than Dan to answer questions.

The "And..." prefix looked kinda weird to me as it's just a small word vertically centered.
Removing it looked a lot better in my opinion and didn't introduce any confusion (it's clear to me that those 30+ other Laravel experts belong to Kirschbaum).
If you guys really think it's better to bring the prefix back, that's ok by me of course, @danharrin @HassanZahirnia.

**Comment by danharrin** [comment]
IMO it looked fine to have a "featured" review with a slightly different design to add some variety, especially since the author of that review also happens to be a pretty famous artist. However, if you truly think it looks bad, we can make them consistent.

With regards to the "and", I think it reads better with it, but I'm happy to be dissuaded against it.

**Comment by zepfietje** [comment]
Regarding the review, I did question why both had a different design.
Though I don't think it necessarily looks really bad.

**Pull request merged**
