### PR TITLE
Update simple map image (jpg)

### PR DESCRIPTION
**Pull request by CodeWithDennis**

### CODE REVIEW

**Comment by CodeWithDennis** [comment]
Hey @saade, thanks for merging my PR! I was about to update the image, so here’s another PR for it.

**Comment by saade** [comment]
@CodeWithDennis 

No worries, could you please remove the sidebar from your screenshot? Also, we usually don't accept just a screenshot as a plugin image, but your plugin is an action so i don't really know how to make it not look like a plain screenshot.

Maybe resize your viewport to remove the sidebar blank space? The form will occupy this space and probably look better.

**Comment by CodeWithDennis** [comment]
> @CodeWithDennis
> 
> No worries, could you please remove the sidebar from your screenshot? Also, we usually don't accept just a screenshot as a plugin image, but your plugin is an action so i don't really know how to make it not look like a plain screenshot.
> 
> Maybe resize your viewport to remove the sidebar blank space? The form will occupy this space and probably look better.

I tried something, is this what you meant?

**Comment by saade** [comment]
that will do it for now, thanks

**Pull request merged**
