### PR TITLE
[Author] - Add muath-ye author and add a laravel-excel package wrapper plugin

### PR DESCRIPTION
**Pull request by muath-ye**

### CODE REVIEW

**Review by saade — CHANGES_REQUESTED** [review]
Hey! Could you please update your bio to be a bit shorter? Around 300-400 characters is ideal.

**Comment by muath-ye** [comment]
@saade I updated the bio

**Comment by saade** [comment]
Your bio contains 1161 characters.

**Comment by muath-ye** [comment]
@saade the bio is less than 400 characters now 😉

**Review by saade — APPROVED** [review]

**Pull request merged**
