### PR TITLE
[Plugin] Add Ecommerce Builder Plugin

### PR DESCRIPTION
**Pull request by 3x1io**

### CODE REVIEW

**Review by saade — CHANGES_REQUESTED** [review]
Hey! Could you please ensure that image URLs in your plugin's `README` file are absolute URLs rather than relative links? Then we can embed them on our website correctly. Thanks!

Please let us know when you've addressed these issues.

**Comment by 3x1io** [comment]
hi @saade thanks for your review it's fixed now you can recheck

**Review by saade — CHANGES_REQUESTED** [review]
Please rename  "Filament CMS" to "Tomato CMS" in both your image and readme.

**Comment by 3x1io** [comment]
@saade oh sorry it's Ecommerce Builder without Filament I will change it.

**Comment by 3x1io** [comment]
@saade it's done now on the repo and PR

**Review by saade — APPROVED** [review]

**Pull request merged**
