### PR TITLE
Add Filament 3.1 news article

### PR DESCRIPTION
**Pull request by alexandersix**
This PR adds a new article for the release of Filament 3.1 and a new author entry (me!)

### CODE REVIEW

**Review by saade — APPROVED** [review]
Hey! Thanks for your contribution. This is a first review that checks if everything is correct and inline with our guidelines. The actual content of your article/ trick needs to be reviewed by another team member before it can be fully merged and published on our website.

**Comment by saade** [comment]
Maybe we can publish this under `filament` author? idk what do you guys think? @alexandersix @danharrin

**Comment by alexandersix** [comment]
@saade I've personally always liked when updates about a project come from people on the team rather than the project account, but that's all my own preference. I know @danharrin has been the one authoring [previous updates](https://filamentphp.com.test/community/danharrin-filament-v3), so I feel like keeping with that pattern might be worthwhile.

**Comment by danharrin** [comment]
Yeah using the actual author profile is good for this, as long as the author bio hints that they are officially involved in the Filament team. The official plugins are different as they are contributed to by the community and multiple Filament team members.

**Pull request merged**
