### PR TITLE
New Plugin - GPT Trix Editor + Author Content

### PR DESCRIPTION
**Pull request by askerakbar**
It is an existing plugin but I just upgraded it to Filament Version 3

Plugin Description:
The GPT Trix Editor is a form field component for the Filament PHP framework that enhances the Trix editor with OpenAI GPT features. 
URL : https://packagist.org/packages/askerakbar/gpt-trix-editor

### CODE REVIEW

**Review by saade — CHANGES_REQUESTED** [review]
Hey! Could you please ensure that image URLs in your plugin's `README` file are absolute URLs rather than relative links? Then we can embed them on our website correctly. Thanks!

Please let us know when you've addressed these issues.

**Comment by askerakbar** [comment]
Done 😊

**Comment by saade** [comment]
@askerakbar Hey, a raw Guthub url looks something like:
https://raw.githubusercontent.com/askerakbar/gpt-trix-editor/main/demo/run-on-selected-text.gif

You can grab these easily by right clicking the image in your readme, and "Open Image in New Tab"

**Comment by askerakbar** [comment]
> @askerakbar Hey, a raw Github url looks something like: https://raw.githubusercontent.com/askerakbar/gpt-trix-editor/main/demo/run-on-selected-text.gif
> 
> You can grab these easily by right clicking the image in your readme, and "Open Image in New Tab"

TIL 
made those changes! thanks man!

**Review by saade — APPROVED** [review]

**Pull request merged**
