### PR TITLE
SuperDuper Filament Starter Kit

### PR DESCRIPTION
**Pull request by 1odp**
A Filament💡 starter point With Custom Theme, Mail Configuration, Filament Shield, Filament Exception, etc..

### CODE REVIEW

**Comment by saade** [comment]
You can use https://banners.beyondco.de to generate a suitable image for your plugin, or create another one using your own design.

Thanks!

**Comment by 1odp** [comment]
I have updated the banner image @saade

**Review by saade — CHANGES_REQUESTED** [review]
Hey! Could you please ensure that image URLs in your plugin's `README` file are absolute URLs rather than relative links? Then we can embed them on our website correctly. Thanks!

Please let us know when you've addressed these issues.

**Comment by 1odp** [comment]
Image url updated

**Pull request merged**
