### PR TITLE
Add GitHub edit link to docs

### PR DESCRIPTION
**Pull request by damms005**

### CODE REVIEW

**Comment by zepfietje** [comment]
Could you share a screenshot of what it looks like now? Maybe we could polish the design a bit. 😄

**Comment by jvkassi** [comment]
Hello,

I was able to deploy this PR without laravel comments.
Here is what it looks like for now.

Screenshot from 2022-10-03 08-28-23

I think we can put it at the bottom like this.

Screenshot from 2022-10-03 08-29-07



What do you think ?

**Comment by danharrin** [comment]
agree

**Comment by zepfietje** [comment]
Also, we should just use the Filament link component for this.

**Comment by jvkassi** [comment]
Okay, is this right ?

```
<x-filament-support::link href="{{ $page->github_link }}" >Edit on GitHub</x-filament-support::link>
```

The result now

Screenshot from 2022-10-03 09-58-13

**Comment by danharrin** [comment]
yes

**Comment by jvkassi** [comment]
@damms005 can you merge https://github.com/damms005/filamentphp.com/pull/1 , when you have time ?

**Comment by zepfietje** [comment]
@jvkassi, it doesn't build on top of this PR, right?

Could you create a pull request?

**Comment by jvkassi** [comment]
Here : https://github.com/filamentphp/filamentphp.com/pull/27

**Comment by zepfietje** [comment]
Closing this in favor of https://github.com/filamentphp/filamentphp.com/pull/27.

Thanks for setting this up, @damms005!

**Pull request closed without merging**
