### PR TITLE
Add heloufir-filament-keycloak-sso plugin

### PR DESCRIPTION
**Pull request by heloufir**

### CODE REVIEW

**Review by awcodes — CHANGES_REQUESTED** [review]
Please remove 'filament' from all slugs and filenames. It is ok in your repo name, but should not be part of anything else.

**Comment by heloufir** [comment]
@awcodes done for the slug and filenames, I just removed `filament`

**Review by awcodes — APPROVED** [review]

**Review by awcodes — APPROVED** [review]

**Review by saade — CHANGES_REQUESTED** [review]
Hey! Your plugin image dimensions must be at least 2560x1440px as per our [Contributing Guide](https://github.com/filamentphp/filamentphp.com#submitting-a-plugin).

Please let us know when you've addressed these issues.

**Comment by heloufir** [comment]
> Hey! Your plugin image dimensions must be at least 2560x1440px as per our [Contributing Guide](https://github.com/filamentphp/filamentphp.com#submitting-a-plugin).
> 
> Please let us know when you've addressed these issues.

Done

**Review by saade — APPROVED** [review]

**Pull request merged**
