### PR TITLE
Plugin: List TomatoPHP Community Plugins

### PR DESCRIPTION
**Pull request by 3x1io**
Hello, in this pull request, I meticulously reviewed and updated all dates, incorporating historical versions to ensure accuracy. The release date now reflects the initial creation of this package for v2 or v3. Apologies for the size of this pull request, but we'll proceed with subsequent updates individually after this one.

List of Plugins:

- [Accounts Builder](https://github.com/tomatophp/filament-accounts)
- [Alerts Sender](https://github.com/tomatophp/filament-alerts)
- Artisan Command Runner [[v2](https://github.com/3x1io/filament-commands),[v3](https://github.com/tomatophp/filament-artisan)]
- [Developer Gate](https://github.com/tomatophp/filament-developer-gate)
- [Locations Seeder](https://github.com/tomatophp/filament-locations)
- Menu Generator [[v2](https://github.com/3x1io/filament-menus), [v3](https://github.com/tomatophp/filament-menus)]
- [Plugins Manager & Generator](https://github.com/tomatophp/filament-plugins)
- [Settings Hub](https://github.com/tomatophp/filament-settings-hub)
- [Splade Integration](https://github.com/tomatophp/filament-splade)
- Translations Manager [[v2](https://github.com/3x1io/filament-translations), [v3](https://github.com/tomatophp/filament-translations)]
- [Types Manager](https://github.com/tomatophp/filament-types)
- User Manager [[v2](https://github.com/3x1io/filament-user), [v3](https://github.com/tomatophp/filament-users)]
- [Wallets Manager](https://github.com/tomatophp/filament-wallet)

### CODE REVIEW

**Comment by 3x1io** [comment]
Any updates?

**Comment by megoxv** [comment]
Why do you not approve with all these plugins that will greatly help the community? This is a developer who deserves appreciation and thanks for this great effort.

**Comment by 3x1io** [comment]
@megoxv thanks for your support, I think it's the reviewing time as they say but, I think it's out of control with 4 weeks for review, but we can still wait for that.

**Comment by saade** [comment]
@megoxv You can still use the plugins even if they haven't been published on the website.

@3x1io The review process takes time, and neither of us work full-time for Filament; we have bills to pay; i review plugins once a week. If you look closely, other plugins were merged during that period. As we've mentioned 3 or 4 times before, if you had submitted one PR per plugin, some of them might have been published by now. Be patient.

**Comment by 3x1io** [comment]
@saade thanks for the replay, it's okay I know that you are working hard, and thanks for your time and support, but I still have a lot of plugins to publish and because of this PR I can't move, so I'm sorry for pushing you, and have a nice time.

**Comment by awcodes** [comment]
In all honesty, even if it's an inconvenience on your part this would all have been easier and most of them could have been approved by now if you submitted each one individually. It might still be faster to do them individually at this point.

**Comment by 3x1io** [comment]
@awcodes yes i know that, and i still have more plugins to publish and i will push it one by one after this PR

**Comment by 3x1io** [comment]
@saade the last change only removed filament-browser from the list because of a security issue inside it, I fixed it but I will do some updates to the package and then resubmit it.

**Review by saade — CHANGES_REQUESTED** [review]
Hey! Could you please ensure that image URLs in your plugin's `README` file are absolute URLs rather than relative links? Then we can embed them on our website correctly. Thanks!

Also, plugin images for Artisan, Translations, Menus, User Resource, Alerts, Settings Hub and Developer Gate are being cropped, and for Splade, Locations Seeder, Types Manager, Plugins Manager & Generator, Accounts Builder and Wallets Manager have a low resolution and looking like they're upscaled.

Please let us know when you've addressed these issues.

**Comment by saade** [comment]
Also, your channels on Discord are indistinguible, i'd rather use `3x1io-foo-plugin` or `tomato-foo-plugin`. But that's not a requirement, only a tip.

image

**Comment by 3x1io** [comment]
All images inside plugins is jpg and on the resolution that you ask me to use, and i add a direct url on the readme 

Check this

Screenshot

If it's on specific plugin please let me know

**Comment by saade** [comment]
> All images inside plugins is jpg and on the resolution that you ask me to use, and i add a direct url on the readme
> 
> Check this
> 
> Screenshot
> 
> If it's on specific plugin please let me know

Right... you've submitted the wrong optimized images, i've removed them and generated again, the're ok now.

The only thing missing is the README images, you're not using the correct raw url:

You're using:
`https://github.com/tomatophp/filament-types/blob/master/arts/3x1io-tomato-types.jpg`

When it should be:
`https://raw.githubusercontent.com/tomatophp/filament-types/master/arts/3x1io-tomato-types.jpg`

Please make the changes and your plugins are ready to be merged.

**Comment by 3x1io** [comment]
@saade it's all done now all images have been fixed.

**Pull request merged**
