### PR TITLE
Update sponsor link

### PR DESCRIPTION
**Pull request by zepfietje**

### CODE REVIEW

**Comment by pxlrbt** [comment]
Ah nice that there is a direct link. Did they update this or was it very hidden? 😅

**Comment by zepfietje** [comment]
I guess you just had to look at the URL. 😂
Came across this in a Tweet (sorry, X post) from James.

**Comment by pxlrbt** [comment]
I checked it last time, but it didn't modify the URL. I think I even submitted feedback to GitHub for this.

**Comment by zepfietje** [comment]
Lol, maybe they added it recently then. 😄

**Pull request merged**
